### ISSUE TITLE
Show Worker: The Table needs to be shortened, some padding required on all the sides

### ISSUE THREAD

**Issue by pmaitra** [cloudheadtechnologies/rs-jewellery#150]

**Comment by sumansarkarwd** [comment]
#3f3f9604511f78b13d04e3d8cfbf7c0f9e301a8c

**Comment by pmaitra** [comment]
Couple of things here: 
1) The Sl No should be replaced by # and column should be thin.
2) As mentioned in this Issue, need Padding on left and right side. The table is taking the entire area (right side frame)
3) Similarly for Edit column. The column header should be "Action" and the column size should be less ( make it thin just so that it can hold Edit)
