### ISSUE TITLE
Receive Allocation: Receive should be done by Pieces

### ISSUE THREAD

**Issue by pmaitra** [cloudheadtechnologies/rs-jewellery#177]
1) Display the Pieces along with the Set ordered
2) User should enter the Pcs ONLY
3) Validation should be modified so that it checks Pcs instead of Sets

**Comment by cloudheadtechnologies** [comment]
#84d878a946a2eb4337681d739bf5833c72977594

**Comment by cloudheadtechnologies** [comment]
#4af2fca1182b9dfd7ba280f544e644f9a4e7e94b
