### ISSUE TITLE
Receive Functionality: Implement Add/Edit

### ISSUE THREAD

**Issue by pmaitra** [cloudheadtechnologies/rs-jewellery#75]
a.	Should be on the right side of the Allocation table (even if it means that scroll is added horizontally)
b.	Receive can be done in phases.
c.	Only the last receive date and receive amount should be displayed
d.	But the DB should store all the receives against a particular allocation

**Comment by sumansarkarwd** [comment]
#198f8623ff6171dcf5d67a61eb91df77f24283e9
