### ISSUE TITLE
Wage Calculation: Implement Add/Edit

### ISSUE THREAD

**Issue by pmaitra** [cloudheadtechnologies/rs-jewellery#76]
a.	Wage has to be calculated in a separate Page
b.	Wage calculation depends on:
i.	No. of Stones allocated and items received
ii.	The Type of Stone allocated
c.	Wage has to be calculated for a month (which means it is a kind of report)

**Comment by sumansarkarwd** [comment]
#63848fdc8bfd3a77e6f6b5919e7f7483bd90026d
